<a href="https://colab.research.google.com/github/Yusvaanth15/AIML-3-7-26/blob/main/AIML_3_7_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 1: Introduction of AIML & Roadmap:

Python fundamentals, Data Science & Data Analytics,Machine Learning, Deep Learning,NLP ,Project and Deployement


Day 2 : Python Fundamentals



In [ ]:
# Variables = a variable is a container used to store data

name = "Yusvaanth"
age = 20
marks = 85.5

print(name)
print(age)
print(marks)

Yusvaanth
20
85.5


In [ ]:
# Data Types: Data types specify the type of value stored in a variable.

name = "Yusvaanth"
age = 20
height = 5.8
student = True

print(type(name))
print(type(age))
print(type(height))
print(type(student))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


In [ ]:
#Functions = A function is a block of code that performs a specific task.


def add(a, b):
    return a + b

result = add(10, 5)

print(result)

15


In [ ]:
# Strings = name = "Python"

print(name)
print(len(name))
print(name.upper())
print(name.lower())

Yusvaanth
9
YUSVAANTH
yusvaanth


In [ ]:
# Tuple = A tuple is an ordered and unchangeable collection of items.

numbers = (10, 20, 30)

print(numbers)
print(numbers[1])


(10, 20, 30)
20


In [ ]:
#1D Array =

In [ ]:
#2D array =

In [ ]:
#3D array =

In [ ]:
#zero array

In [ ]:
#Ones Array

In [ ]:
#Indexing = Acessing Indivitual elements

a = np.array([19,20,22,24])
print(a[3])

24


In [ ]:
#2D Indexing


In [ ]:
#Slicing = Accessing Multiple Elements

In [ ]:
# Array Addition = Mathematical Formula
import numpy as np

a = np.array([3,4,5,2,])
b = np.array([5,6,7,8])
c = a + b
print(c)

[ 8 10 12 10]


In [ ]:
# Array Subtraction

a = np.array([1,2,3,4])
b = np.array([8,6,4,2])
c = a - b
print(c)

[-7 -4 -1  2]


In [ ]:
# Array Multiplication

a = np.array([1,0,6,5])
b = np.array([9,5,2,1])
c = a * b
print(c)

[ 9  0 12  5]


In [ ]:
# Array Division

a = np.array([1,0,6,5])
b = np.array([9,5,2,1])
c = a / b
print(c)

[0.11111111 0.         3.         5.        ]


In [ ]:
# Matrix Addition

import numpy as np

A = np.array([[1, 3],
              [4, 5]])

B = np.array([[1, 4],
              [6, 4]])

print(A + B)

[[ 2  7]
 [10  9]]


In [ ]:
# Matrix Subtraction

import numpy as np

A = np.array([[1, 3],
              [4, 5]])

B = np.array([[1, 4],
              [6, 4]])

print(A - B)

[[ 0 -1]
 [-2  1]]


In [ ]:
# Mode = Most Frequently accuring value,
#Numpy has no direct mode Function


In [ ]:
#Standard Deviation = Measure the speed of data arounnd the mean


In [ ]:
#Sum = Add all Element

In [ ]:
# Maximum and Minimum

import numpy as np

A = np.array([10, 20, 5, 40, 15])

print("Maximum =", np.max(A))
print("Minimum =", np.min(A))

Maximum = 40
Minimum = 5


In [ ]:
# Transpose of Matrix (Simple Example)

import numpy as np

A = np.array([[1, 2],
              [3, 4]])

print(A.T)


[[1 3]
 [2 4]]


Important Mathematical Concepts for AIML using Numpy

In [ ]:
#Scaler

import numpy as np

scaler = np.array(10)

print("Scaler :", scaler)
print("Dimension :", scaler.ndim)

Scaler : 10
Dimension : 0


In [ ]:
# vectors

import numpy as np

vector = np.array([10])

print("Vector :", vector)
print("Dimension :", vector.ndim)

Vector : [10]
Dimension : 1


In [ ]:
# dot Product = the dot product multiplies the two matrices or vector

import numpy as np

A = np.array([[1, 3],
              [4, 5]])

B = np.array([[1, 4],
              [6, 4]])

print(np.dot(A, B))

[[19 16]
 [34 36]]


In [ ]:
# Mean
import numpy as np

data = np.array([10, 20, 30, 40, 50])

print("Mean =", np.mean(data))

Mean = 30.0


In [ ]:
# Varieance =varience measures how far data is spread from the mean

import numpy as np

data = np.array([2, 4, 6, 8, 10])

print(np.var(data))

8.0


In [ ]:
# Covarieance = Covariance is a statistical measure that shows how two variables change together( moves forward means positive and moves backward means negative)

import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

print(np.cov(x, y))

[[ 2.5  5. ]
 [ 5.  10. ]]


In [ ]:
# Corelation = Corelation measures the strength of the relationship between two variables

import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

print(np.corrcoef(x, y))

[[1. 1.]
 [1. 1.]]


In [ ]:
# Eigenvalues and Eigenvector (Eigenvalue: A value associated with a matrix.
#Eigenvector: A vector whose direction remains unchanged after matrix multiplication.)

import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
eigenvalues,eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)


[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
#Probability distributuion = Probability distribution shows the probability of all possible outcomes.


In [ ]:
# Normal distributuion

In [ ]:
# Binomial Distribution

In [ ]:
# Uniform Distribution

In [ ]:
# polynomial Distribution

In [ ]:
# Gradient Descent = Gradient Descent is used to minimize the error by updating the model parameters step by step.

x = 10
learning_rate = 0.1

for i in range(10):
    x = x - learning_rate * (2 * x)

print("Minimum Value:", x)

Minimum Value: 1.0737418240000003


In [ ]:
# Linear Regression

import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = 3 * x + 2

coef = np.polyfit(x, y, 1)

print("Slope:", coef[0])
print("Intercept:", coef[1])

Slope: 3.0
Intercept: 2.000000000000001


In [ ]:
# Normalization = Normalisation rescales values toa fixed range

In [ ]:
# Standardisation = standardisation transfers data to have a mean of  0 and a standard deviation of 1

PANDAS

In [ ]:
# Data Frame =
# 4 rows and 4 coloumns
data = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

for row in data:
    print(row)


[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]


In [ ]:
# 5 rows and 5 columns

data = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
]

for row in data:
    print(row)


[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[11, 12, 13, 14, 15]
[16, 17, 18, 19, 20]
[21, 22, 23, 24, 25]
